repos: []
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v6.0.0
#     hooks:
#       - id: trailing-whitespace
#       - id: end-of-file-fixer
#       - id: check-yaml
#       - id: check-added-large-files

  # - repo: https://github.com/nicklockwood/SwiftFormat
  #   rev: 0.53.5
  #   hooks:
  #     - id: swiftformat
  #       args: ["--config", "ios/.swiftformat"]

  # - repo: https://github.com/realm/SwiftLint
  #   rev: 0.54.0
  #   hooks:
  #     - id: swiftlint
  #       args: ["--strict", "--config", "ios/.swiftlint.yml"]
  #       files: \.swift$

  # - repo: https://github.com/ncipollo/pre-commit-ktlint
  #   rev: v1.1.0
  #   hooks:
  #     - id: ktlint
  #       args: ["--android"]
